### PR TITLE
EARTH-648: Video player title updates

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Adds better handling for the title overlay when the hero banner is a video

# Needed By (Date)
- Sometime next sprint

# Urgency
- Not sure.

# Steps to Test

1. Check out this branch and EARTH-648 of stanford_paragraph_types
2. Clear all caches. Really really clear all caches.
3. Review the home page on mobile for placement of the title below the video 
4. Review the home page on desktop for placement of the title over the video
5. Play the video to see the title fade out
6. Pause the video to see the title fade back in
7. Create a second and third video on the page
8. Test to see that the titles align below the video with other content on the page
9. Test to see that the titles independently fade in and out as each video is playing

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by ksharp-drupal** [comment]
Works as advertised, but one thing I noticed - when sized for mobile, the titles drop below the videos correctly, but they still fade out on play and fade in on pause. Should the fade out/fade in only happen when the titles are placed over the video?

**Comment by sherakama** [comment]
@ksharp-drupal Good call.

I have added the window screen size condition to ensure the title only fades out on non-mobile.

**Review by ksharp-drupal — APPROVED** [review]
This is pretty cool.

**Comment by sherakama** [comment]
Thanks @ksharp-drupal 

Have a great long weekend.

**Pull request merged**
