### PR TITLE
EARTH-1303: hover state on postcard

### PR DESCRIPTION
**Pull request by buttonwillowsix**
# READY FOR REVIEW

# Summary
- Adding a hover state to arrows for postcard

# Needed By (Date)
-Next push

# Urgency
- Non-urgent

# Steps to Test

1. Checkout this branch
2. Navigate to a page that has a postcard (for example, /farm)
3.  Check for color and hover motion change

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- Earth-1303

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by buttonwillowsix** [comment]
@aaroncole can you review?

**Review by aaroncole — APPROVED** [review]
Looks good to me.

**Comment by aaroncole** [comment]
@buttonwillowsix Please resolve the package-lock.json conflict

**Comment by buttonwillowsix** [comment]
> @buttonwillowsix Please resolve the package-lock.json conflict

@aaroncole Merge conflict resolved. Ready for re-review/merge!

**Pull request merged**
